apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.task.serviceAccount.name }}"
  {{- if and (hasKey .Values.jxRequirements.cluster "project") (hasKey .Values.jxRequirements.cluster "clusterName") (eq .Values.jxRequirements.cluster.provider "eks") }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.jxRequirements.cluster.project }}:role/{{ .Values.jxRequirements.cluster.clusterName }}-tekton-bot
  {{- else if eq .Values.jxRequirements.cluster.provider "gke" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.jxRequirements.cluster.clusterName }}-tekton@{{ .Values.jxRequirements.cluster.project }}.iam.gserviceaccount.com
  {{- else }}
  annotations: {}
  {{- end }}
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
secrets:
  {{- if and (hasKey .Values.jxRequirements.cluster "project") (hasKey .Values.jxRequirements.cluster "clusterName") (eq .Values.jxRequirements.cluster.provider "gke") }}
  - name: docker-registry-auth
  - name: tekton-git
  {{- else }}
  - name: tekton-container-registry-auth
  - name: tekton-git
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ required .Values.task.serviceAccount.errMSg .Values.task.serviceAccount.name }}"
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  {{- if and (hasKey .Values.jxRequirements.cluster "project") (hasKey .Values.jxRequirements.cluster "clusterName") (eq .Values.jxRequirements.cluster.provider "eks") }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.jxRequirements.cluster.project }}:role/{{ .Values.jxRequirements.cluster.clusterName }}-tekton-bot
  {{- else if eq .Values.jxRequirements.cluster.provider "gke" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.jxRequirements.cluster.clusterName }}-tekton@{{ .Values.jxRequirements.cluster.project }}.iam.gserviceaccount.com
  {{- else }}
  annotations: {}
  {{- end }}
secrets:
  {{- if and (hasKey .Values.jxRequirements.cluster "project") (hasKey .Values.jxRequirements.cluster "clusterName") (eq .Values.jxRequirements.cluster.provider "gke") }}
  - name: docker-registry-auth
  - name: tekton-git
  {{- else }}
  - name: tekton-container-registry-auth
  - name: tekton-git
  {{- end }}

