apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.task.serviceAccount.name}}"
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "tekton-bot"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.task.serviceAccount.name}}"
    namespace: jx
