kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gradle-home
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 2Gi
