kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaniko-cache
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: nfs
  resources:
    requests:
      storage: {{ .Values.kaniko.storage }}
