kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.reports.pvc.name }}
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.reports.pvc.storage.size }}
