kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "trivy"
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 1Gi
