jx:
  images:
    boot: gcr.io/jenkinsxio/jx-boot:3.1.103
    cli: gcr.io/jenkinsxio/jx-cli:3.1.103
    preview: gcr.io/jenkinsxio/jx-preview:0.0.138
    changelog: gcr.io/jenkinsxio/jx-changelog:0.0.17
    release: gcr.io/jenkinsxio/jx-release-version:1.0.42
    promote:  gcr.io/jenkinsxio/jx-promote:0.0.164

jxRequirements:
  cluster:
    provider: gke
    project:
    clusterName:
