jx:
  images:
    boot: gcr.io/jenkinsxio/jx-boot:3.1.169
    cli: gcr.io/jenkinsxio/jx-cli:3.1.169
    preview: gcr.io/jenkinsxio/jx-preview:0.0.143
    changelog: gcr.io/jenkinsxio/jx-changelog:0.0.27
    release: gcr.io/jenkinsxio/jx-release-version:1.0.46
    promote:  gcr.io/jenkinsxio/jx-promote:0.0.179

jxRequirements:
  cluster:
    provider: gke
    project:
    clusterName:

reports:
  ingress:
    hostname:
  pvc:
    name: pipeline-reports
    storage:
      size: 1Gi


nginx:
  serverBlock: |-
    server {
      listen 8080;
      location / {
        root /pipeline-reports;
        autoindex on;
      }
    }
  extraVolumes:
    - name: pipeline-reports-dir
      persistentVolumeClaim:
        claimName: pipeline-reports
  extraVolumeMounts:
    - name: pipeline-reports-dir
      mountPath: /pipeline-reports
