jx:
  images:
    boot: ghcr.io/jenkins-x/jx-boot:3.1.266
    # boot version where "jx gitops pr comment" is not broken
    boot_comment: gcr.io/jenkinsxio/jx-boot:3.1.43
    cli: ghcr.io/jenkins-x/jx-cli:3.1.266
    preview: gcr.io/jenkinsxio/jx-preview:0.0.159
    changelog: gcr.io/jenkinsxio/jx-changelog:0.0.34
    release: gcr.io/jenkinsxio/jx-release-version:2.2.3
    promote:  ghcr.io/jenkins-x/jx-promote:0.0.237

task:
  images:
    gradle: "gradle:6.3.0-jdk11"
    node: "gcr.io/jenkinsxio/builder-nodejs12x:latest"
    gitleaks: "zricethezav/gitleaks:v7.1.0"

jxRequirements:
  cluster:
    provider: gke
    project:
    clusterName:

reports:
  ingress:
    hostname:
  pvc:
    name: pipeline-reports
    storage:
      size: 1Gi


nginx:
  serverBlock: |-
    server {
      listen 8080;
      location / {
        root /pipeline-reports;
        autoindex on;
      }
    }
  extraVolumes:
    - name: pipeline-reports-dir
      persistentVolumeClaim:
        claimName: pipeline-reports
  extraVolumeMounts:
    - name: pipeline-reports-dir
      mountPath: /pipeline-reports
