storageClass: nfs

jxRequirements:
  cluster:
    provider: gke
    gitKind: github
    project:
    clusterName:

kaniko:
  storage: 1Gi

gradle:
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
  sidecar:
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi