kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: tkn-pipeline-controller
  labels:
    release: "monitoring"
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: tekton-pipelines-controller
