apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: conventional-commits
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "conventional-commits"
    tekton.dev/displayName: "conventional-commits"
spec:
  description: >-
    build
  workspaces:
    - name: source
      description: sources dir
  params:
    - name: MARDOWN_HEADER
      type: string
      description: header of comment
      default: "[Conventional Commits](https://www.conventionalcommits.org): **Check Failed** :angry:"
    - name: PR_NUMBER
      type: string
      description: Pull Request Number to left comment
      default: ""
    - name: FAIL
      type: string
      description: Pull Request Number to left comment
      default: "false"
    - name: LINTER_IMAGE
      type: string
      description: image who scanning commits
      default: "aevea/commitsar:0.16.0"
    - name: JX_BOOT
      default: "{{ .Values.jx.images.boot }}"
    - name: RESULTS_REPORT_PATH
      default: ".conv-commits-report.json"
    - name: RESULTS_MARKDOWN_REPORT_PATH
      default: ".conv-commits-markdown.report"
    - name: PULL_BASE_SHA
      default: ""
    - name: PULL_PULL_SHA
      default: ""
  results:
    - name: passed
      description: is passed
  steps:
    - name: conventional-commits-check
      image: $(params.LINTER_IMAGE)
      workingDir: $(workspaces.source.path)
      env:
        - name: PULL_BASE_SHA
          value: "$(params.PULL_BASE_SHA)"
        - name: PULL_PULL_SHA
          value: "$(params.PULL_PULL_SHA)"
      script: |
        if commitsar $PULL_BASE_SHA...$PULL_PULL_SHA > "$(params.RESULTS_REPORT_PATH)"; then
          echo -n "true" > $(results.passed.path)
        else
          echo -n "false" > $(results.passed.path)
        fi
    - name: conventional-commits-prepare-report
      image: $(params.LINTER_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        echo "=== Building mardown"
        export COLUMNS=$(cat $(params.RESULTS_REPORT_PATH) | grep "|" | awk -F"|" '{printf "%s | %s | %s", $2, $3, $4;} {print ""}' | grep -v -e '^[[:space:]]*$' | tail -n +2 | grep '[[:alnum:]]')
        echo -e "$(params.MARDOWN_HEADER) \n \n HASH | ERROR | MSG \n --|--|-- \n $COLUMNS" > "$(params.RESULTS_MARKDOWN_REPORT_PATH)"
    - name: conventional-commits-comment
      image: "{{ .Values.jx.images.boot }}"
      workingDir: $(workspaces.source.path)
      script: |
        export REPO_URL="$(git config --get remote.origin.url)"

        if [ -z "$(params.PR_NUMBER)" ]; then
            echo "No PR_NUMBER parameter provider, skipping commet."
          else
            if ! "$(cat $(results.passed.path))" ; then
              jx gitops pr comment --pr="$(params.PR_NUMBER)" --comment="$(cat $(params.RESULTS_MARKDOWN_REPORT_PATH))"
            fi
        fi
    - name: conventional-commits-final
      image: $(params.JX_BOOT)
      workingDir: $(workspaces.source.path)
      script: |-
        if "$(params.FAIL)" ; then
          if ! "$(cat $(results.passed.path))" ; then
            exit 1
          fi
        fi
