kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: loki
  labels:
    release: "monitoring"
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: loki
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 1m

