kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: promtail
  labels:
    release: "monitoring"
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      "app.kubernetes.io/name": promtail
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 1m

