{
 "title": "Pipeliens",
 "tags": [
  "pipelines",
  "tekton"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Basic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running pipelines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tekton_running_pipelineruns_count",
     "legendFormat": "Active pipelines"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tekton_running_taskruns_count", "legendFormat": "Active Tasks" }
   ]
  },
  {
   "title": "Success pipelines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tekton_pipelinerun_count{status=\"success\"}[$__rate_interval]))",
     "legendFormat": "rate"
    },
    {
     "expr": "tekton_pipelinerun_count{status=\"success\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Failed pipelines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tekton_pipelinerun_count{status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "rate"
    },
    {
     "expr": "tekton_pipelinerun_count{status=\"failed\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Releases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tekton_pipelinerun_duration_seconds_count{pipelinerun=~\"release.*\"}) by (pipeline, status)"
    },
    {
     "expr": "sum(tekton_pipelinerun_duration_seconds_count{pipelinerun=~\"release.*\"}) ",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Releases Success VS Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tekton_pipelinerun_duration_seconds_count{pipelinerun=~\"release.*\", status=\"failed\"}) ",
     "legendFormat": "success"
    },
    {
     "expr": "sum(tekton_pipelinerun_duration_seconds_count{pipelinerun=~\"release.*\", status=\"success\"}) ",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Pipelines AVG duration [sec]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(tekton_pipelinerun_duration_seconds_sum) by (pipeline) / 60) / sum(tekton_pipelinerun_duration_seconds_count) by (pipeline)",
     "legendFormat": " {{` {{pipeline}} `}} "
    }
   ]
  },
  {
   "title": "Task AVG duration [min]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(tekton_pipelinerun_taskrun_duration_seconds_sum) by (task) / 60) / sum(tekton_pipelinerun_taskrun_duration_seconds_count) by (task)",
     "legendFormat": " {{` {{task}} `}} "
    }
   ]
  }
 ]
}