apiVersion: v1
kind: Secret
metadata:
  name: github-sdlc-app
type: Opaque
data:
  appId: {{ .Values.github.appId | b64enc | quote }}
  installId: {{ .Values.github.installId | b64enc | quote }}
  privateKey: {{ .Values.github.privateKey | b64enc | quote }}
