apiVersion: v1
kind: Secret
metadata:
  name: sonar
type: Opaque
data:
  sonar-login: {{ .Values.sonar.login | b64enc | quote }}
  sonar-host-url: {{ .Values.sonar.hostUrl | b64enc | quote }}
  sonar-scm-provider: {{ .Values.sonar.scmProvider | b64enc | quote }}
  sonar-organization: {{ .Values.sonar.organization | b64enc | quote }}
